### ISSUE TITLE
typos in path to query files

### ISSUE THREAD

**Issue by victorkane** [rodneylab/sveltekit-headless-wordpress#1]
Congratulations on excellent tutorial! Wanted to draw your attention to some typos for the path names given to several query files in their presentation (not in the path-name of import statements in other files):

- All queries are correctly imported from `$lib/graphql/query/` folder !
- All import statements in various `*.ts` files (like `src/routes/+page.server.ts` for example) are correct!
- First one is correct:
> We’ve added links to new source files! Let’s get those saved then look at what we have! Create a src/lib/grapql/query folder and add the GraphQL query we run in this page there in a posts.graphql file
- However, the path-names of query files shown in several other places are incorrect:
> Let’s start by adding the page GraphQL query in a new src/lib/graphql/page.graphql file 
  - _(the name of file is incorrect in the heading, similarly omitting `query`, should be: src/lib/graphql/query/page.graphql (that is how it is correctly imported)_
>
> Like for the privacy page, we will start by creating a new GraphQL query for posts. This time we will include quite a bit of Yoast SEO generated metadata too. Create src/lib/graphql/post.graphql and add the following content 
  - (_same mistake_)

So, given that there is no repo for us to depend on as we follow this wonderful course, I think it would be great for these typos to be fixed.

Thanks!

**Comment by rodneylab** [comment]
Thanks @victorkane for your kind feedback and also for reporting this typo. It might have taken me a little while to spot it, so I am sure other developers following the tutorial will appreciate this.

I have just pushed the corrected version, and it should feed through shortly.  I hope you did not lose too much time on trying to work out what was going on.

I will close the issue, but please let me know if you feel it has not been solved. Also get in touch if there is another topic you would like to see a tutorial on!

Kind regards,
Rodney
